
<?php  $accountsFriends = $this->accounts; ?>
<?php  $accounts = $this->accounts; ?>
<?php  $allactivity = $this->results; ?>
<?php  $usernamesTemp = $this->usernames; ?>
<?php  $imgPrefix = $this->imgPrefix; ?>
<?php  $seriesColor = array("#FF9900", "#00F", "#BB0000"); ?>
<?php 
	$sum=0;
	foreach ($this->allActivity as $activityTemp){
	$sum = $sum +  (1*$activityTemp->glass)+(2*$activityTemp->plastic)+(3*$activityTemp->aluminium);
}?>
<header class="desktop-header navbar-fixed-top ">
	<div class="container">
			<img alt="Sociallgreen" title="Sociallgreen" id="logo" class="pull-left span2" src="<?php echo $this->baseUrl("images/logo.png"); ?>"/>
			<?php echo $this->LoggedInAs(); ?>
	</div>
</header>

<!-- Modal Badges -->
<div id="Modalleaderboard" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="ModalBadgesLabel" aria-hidden="true">
  <div class="modal-header lead-background">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove icon-white"></i></button>
    <h6 id="ModalBadgesLabel" class="title-leaderboard">Leaderboard</h6>
  </div>
  <div class="modal-body">
						

  </div>
  <!-- <div class="modal-footer">
    <button class="btn btn-glor pull-left" data-dismiss="modal" aria-hidden="true">Close</button>
  </div> -->
</div>

<div id="projects" class="page">
		<section class="container-fluid">
			<div class="row-fluid">
				<section class="container">
					<div class="row-fluid">
					<article class="span3 add-top remove-left">
							<div class="row-fluid">
								<article class="span11">
							    <table class="table table-striped ">
							    	<thead class="lead-background" >
							    		<tr>
							    			<!-- <a class="btn btn-glor2 btn-small" data-toggle="modal" data-target="#Modalleaderboard"><span class="title-leaderboard">Leaderboard</span></a> -->
	      									<!-- <th><span class="title-leaderboard">Leaderboard</span></th> -->
	      									<th><a class="" href="" data-toggle="modal" data-target="#Modalleaderboard"><span class="title-leaderboard">Leaderboard</span></a></th>
	      								</tr>
							    	</thead>
							    	<tbody>
							    	<?php $place = 1;
									$sup = array(1=>"st",2=>"nd",3=>"rd");
									?>
									
									
					                <?php  foreach ($accounts as $account) { ?>
					                    	
					                    	<tr>
					                    		<td>
					                    			<span class="text-leaderboard text-success"><?php echo $place; ?></span>  <!-- <sup><?php //if ($place<4) { echo $sup[$place];} else {echo "th";} ?></sup></span> -->
						                    		<!-- <img style="width: 32px;height: auto; display: inline-table;" src='<?php echo $this->baseUrl("images/Leaderboard/".$place.".png"); ?>'> -->
					                    		
						                    		<a class="thumbnail" style="margin-left:5px;margin-top:2px;display: inline-table;" title="<?php echo $account->username; ?>" href="<?php echo $this->baseUrl('account/profile/').'?user='.$account->username;?>">
						                    		<!-- <img class="media-object img-leaderboard" src="<?php //echo $this->baseUrl($imgPrefix."thumb-".$account->avatar); ?>"></a> -->
					                    			 <img class="media-object img-leaderboard" src="<?php echo $this->controller->thumbimagesfb($account->avatar,$this->baseUrl()); ?>"></a>
					                    		
					                    			<p style="margin-bottom: 0px !important; margin-left:5px;color:black; display: inline-table;"><strong><a title="<?php echo $account->username; ?>" href="<?php echo $this->baseUrl('account/profile/').'?user='.$account->username;?>"><?php echo $account->username; ?></a></strong><br><i><?php echo $account->leafs;?> leaves</i>
					                    		</td>
											</tr>
										
									<?php $place++; } ?>
									</tbody>
	    						</table>
    						</article>
							</div>
    						
    						<div class="row-fluid">
								<article class="span11 cubicles rounded-bottomleft rounded-topleft text-right text-right">
									<span class="score-heading-white"><?php echo $sum;?></span><br><span>total leaves saved</span>
								</article>
							</div>
    						
					</article>
					
					<article class="span9 custom-margin-top-3 add-left">
						<div class="row">
							<article class="span12">
							<div class="tabbable">
								<ul class="nav nav-tabs">
									    <li class="active"><a href="#Diagram" data-toggle="tab" >Diagram</a></li>
									    <li><a href="#Activity" data-toggle="tab">Activity</a></li>
									    
								</ul>
								
					            <div class="tab-content" id="myTabContent">
									
									<!-- Diagram Content -->
					            	<div class="tab-pane active" id="Diagram">
					            		<h4 class="col-high">Check the progress of our users - Activity over time</h4>
					            		
					    					<div id="chartdiv"> </div>
					    					<?php // foreach($this->paginator as $record)
										    //{
										     //   echo $record['email'].'\n';
										    //}
										    //echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
										    ?>
										    <div id="diagramUserNamesPanel" class="row-fluid">
										    	<div class="span8 ">
										    	<ul>
										    		<?php 
										    			$colorCounter = 0;
										    			foreach ($usernamesTemp as $fullName){
															echo "<li><span style='background-color:".$seriesColor[$colorCounter]."'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span>".$fullName."</span></li>";
															$colorCounter++;
														}
										    		?>
										    	</ul>
										    	</div>
										    </div>
					              	</div>
				              	
									<!-- Activity Content -->
									<div class="tab-pane" id="Activity">
										
										<!-- Activity Container -->
										<h4 class="col-high">Latest recycling!</h4>
										
										<table class="table table-hover table-stripped">
										<?php  foreach ( $allactivity as $activity) { ?>
										<!--  <div class="media">
						                    <a class="pull-left" href="<?php //echo $this->baseUrl('account/profile/').'?user='.$activity->username;?>">
						                    <img class="media-object" src="http://placehold.it/64x64">
						                    </a>
											<div class="media-body">
						    					<h4 class="media-heading"><?php //echo $activity->username;  ?></h4>
						    					 just saved <?php //echo $activity->quantity;?>
						    				</div>
						
										</div> 
										-->
											<?php if ($activity->quantity>0) {?>
											<tr>
												<td>
													<a class="pull-left" href="<?php echo $this->baseUrl('account/profile/').'?user='.$activity->username;?>">
						                    			<!-- <img class="media-object thumbnail avatar" src="<?php //echo $this->baseUrl($imgPrefix."thumb-".$activity->avatar);?>"> -->
						                    			<img class="media-object thumbnail avatar" src="<?php echo $this->controller->thumbimagesfb($activity->avatar,$this->baseUrl()); ?>">
						                    		</a>
												</td>
												<td style="vertical-align: middle;">
													<?php /* echo ucfirst($activity->username);  ?> saved <?php echo 1*$activity->glass+2*$activity->plastic+3*$activity->aluminium; ?> leafs on <?php echo date("d-M",strtotime($activity->date)) ?>! <span class="muted">(aluminium: <?php echo $activity->aluminium." * 3 leafs, plastic:".$activity->plastic." * 2 leafs, glass:".$activity->glass ?> * 1 leaf)</span> */ ?>
													<?php echo ucfirst($activity->username);  ?> saved <?php echo 1*$activity->glass+2*$activity->plastic+3*$activity->aluminium; ?> leafs on <?php echo date("d-M",strtotime($activity->date)) ?>! <span class="muted">
													<br><img class="img-materials-height" src="<?php echo $this->baseUrl("/images/materials/alum.png");?>"> = <?php echo $activity->aluminium; ?>
													<img class="img-materials-height" src="<?php echo $this->baseUrl("/images/materials/plastic.png");?>"> =<?php echo $activity->plastic; ?>
													<img class="img-materials-height" src="<?php echo $this->baseUrl("/images/materials/glass.png");?>"> = <?php echo $activity->glass; ?></span>
												</td>
											</tr>
										
											<?php } ?>
										<?php } ?>
										</table>
										<span class="pull-left"><?php echo $this->paginationControl($this->results, 'Sliding', 'pagination.phtml'); ?></span>
									</div>
									
								</div>
							</div>
							</article>
						</div>  
					</article>
					</div>
				</section><!-- container : ends -->
			</div><!-- row-fuild : ends -->
		</section> <!-- container-fluid : ends-->
	</div> <!-- projects : ends -->

<script>
<?php 

	$count=1;
	$lines = "[";
	foreach ($this->activity as $act) {
		echo "var line".$count."=".str_replace('"', "", $act).";";
		//echo "<br>";
		$lines.= " line".$count.",";
		$count++;
	}
	$lines = rtrim($lines, ",");
	$lines.="]";
	

	$usernames = "[";
	foreach ($usernamesTemp as $usr) {
		$usernames.='"'.$usr.'",';
	}
	$usernames = rtrim($usernames, ",");
	$usernames.="]"; 

	$ticks = "[";
	$i = 1;
	foreach ($this->dates as $date){
		$ticks.='['.$i.',"'.date("d-M", strtotime($date)).'"],';
		$i++;
	}
	$ticks = rtrim($ticks,",");
	$ticks.="]";
?>

var labels = <?php echo $usernames; ?>;
var ticks = <?php echo $ticks; ?>; 
var plot1 = $.jqplot('chartdiv', <?php echo $lines ?>, {
	  animate: true,
      // Will animate plot on calls to plot1.replot({resetAxes:true})
      animateReplot: false, 
      seriesColors:<?php echo json_encode($seriesColor); ?>,
   	 seriesDefaults: { 
     // showMarker:false,
     // pointLabels: {show:false},
      rendererOptions: {smooth: true} 
    },
    /*legend: {
        show: false,
        renderer: $.jqplot.EnhancedLegendRenderer,
        placement: "insideGrid",
        labels: labels,
        location: "ne",
        rowSpacing: "1px",
        seriesToggle : 'normal',
        showSwatches : true,
        showLabels: false
    },*/
    /*highlighter: {
        show: true,
        //sizeAdjust: 7.5,
        bringSeriesToFront: false
    },*/	
    /*grid: {
        drawGridLines: true},*/
    axes: {
        xaxis: {
        	labelRenderer: $.jqplot.CanvasAxisLabelRenderer,
        	tickRenderer: $.jqplot.CanvasAxisTickRenderer,
            pad: 1,
            tickOptions: {
                showGridline: true,
                angle: -30
            },
            ticks: ticks
        },
        yaxis: {
        	labelRenderer: $.jqplot.CanvasAxisLabelRenderer,
            min: 0,
            //max: 100,
            //label: 'Points',
            tickOptions: {
              showGridline: true//,
            //  suffix: '%'
            }
        }
    }
	});

</script>