<?php /* 
<div class="row-fluid">
	<div class="span6 offset3 well">
		<?php $this->Errors($this->errors); ?>
		<?php echo $this->form; ?>
	</div>
</div>
*/ ?>

<div id="register" class="page">
	<div class="row-fluid">
		<article class="span1 offset1">
			<a class="tp-leftarrow large" href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index' ), null, TRUE); ?>"><div class="tp-leftarrow large"></div></a>
		</article>
	</div>
	<section class="container">
		<div class="row-fluid">
			<article class="span6 offset3">
		 		
		 		<span class="main-heading" style="font-size: 60px;">Register</span>
		 		
		 		<?= $this->Errors($this->errors); ?>
		 		
				<?php echo $this->form->setAction($this->url(array('controller'=>'account', 'action'=>'register' ), null, TRUE)); ?>
				<!-- <p>- or -<br>
				<button id="fbc-login-button">Login with 0Facebook</button>
				</p>
				-->
			</article><!-- span12 : ends -->
		</div><!-- row-fuild : ends -->
	</section> <!-- container-fluid : ends-->
</div> <!-- team : ends -->