<form class="form-horizontal" id="login" action="<?= $this->element->getAction(); ?>" method="<?= $this->element->getMethod(); ?>">
<div class="control-group">
	<?= $this->element->username; ?>
</div>
<div class="control-group">
	<?= $this->element->password; ?>
</div>
<div class="control-group">
	<?= $this->element->login; ?>
</div>
</form>
<a href="<?php echo $this->url(array('controller'=>'auth','action'=>'recover'))?>">Did you forget your account?</a>