<?php /*<div class="row-fluid ">
	<div class="span2 offset2" >
				<h2 class=""><span class="purplefonts">Social</span><span class="greenfonts">Green</span></h2>
				</div>
				<div class="span4" >
				<p>He has graduated from the Department of Economics of Aristotle university. 
				During those years he attended student exchange programmes in Sweden and France gaining multicultural experiences. 
				By October 2012 he holds an MSc at "Informatics and Management" from the Computer Science Departement of Aristotle. 
				His working experience include traineeships at Greek ministry of foreign affairs, Hellenic post bank and a Consulting company. 
				He is a co-founder of SocialGreen where he works on the Business Development of the project.</p>
				<button class="btn btn-large btn-primary" type="button">Host the pilot version!</button>
	</div>
</div>--------------

<div class="row-fluid ">
	<div class="span8 offset2" >
				<h2 class="text-center" >Are you an Organisation ?</h2>
				
				<p class="text-center" >Want to enagage your people into recycling ?</p>
				<br>
				
	</div>
</div>
<div class="row-fluid ">
	<div class="span3 offset2" >
		<h3>What is the bin?</h3>
		<img class="img-polaroid" style="width:200px;margin:0px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
	<div class="span4 " style="margin-top:60px;" >
		<blockquote>
		<p>He has graduated from the Department of Economics of Aristotle university. 
		</p>
		<br>
		</blockquote>
	</div>
</div>
<div class="row-fluid ">
	<div class="span4 offset2 " style="margin-top:60px;">
		<blockquote class="pull-right">
		<p>He has graduated from the Department of Economics of Aristotle university. 
		</p>
		<br>
		</blockquote>
	</div>
	<div class="span3 text-right" style="margin-bottom: " >
		<h3>Where can i get one?</h3>
		<img class="img-polaroid pull-right" style="width:200px;margin:10px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
</div>
<div class="row-fluid ">
	<div class="span3 offset2" >
		<h3 class="text-left">What do i win?</h3>
		<img class="img-polaroid" style="width:200px;margin:10px 2px;" src="<?php echo $this->baseUrl("images/teamPhotos/photos/mikres/antw.jpg"); ?>">
	</div>
	<div class="span4 " style="margin-top:60px;" >
		<blockquote>
		<p >He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
		</blockquote>			
	</div>
</div>
<div class="row-fluid ">
	<div class="span4 offset4" >
		<button class="btn btn-large btn-primary" type="button">Interested?</button>
	</div>
</div>
*/?>
<div class="row-fluid " style="margin-top: 50px;">
	<div class="span6 offset3 text-center" >
				<span class="titlos-kentrikos">ARE YOU<br></span>
				<span class="titlos-kentrikos2">AN ORGANISATION?<br></span>
				<span class="titlos-kentrikos3">WANT TO ENGAGE YOUR PEOPLE INTO RECYCLING..</span>
				<br>
				
	</div>
</div>
<div class="row-fluid ">
	<div id="xoros-aristera" class="span3 offset1">
		<h3 class="titlos-eikonas" >The Sociallbin</h3>
		<img class="img-rounded" style="width:250px;margin:0 0 10px 0px;" src="<?php echo $this->baseUrl("images/sketch/kados2.png"); ?>">
		<p class="getinvolvedp hidden">He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
	</div>

	<div class="span4 text-center">
		<img class="velos-aristera hidden-tablet hidden-phone" src="<?php echo $this->baseUrl("images/sketch/velos-l.png"); ?>">
		<div><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'submit-Contact'), null, TRUE); ?>"><button  class="btn btn-large btn-primary" type="button">Interested?</button></a></div>
		<img class="velos-dexia hidden-tablet hidden-phone" src="<?php echo $this->baseUrl("images/sketch/velos-r.png"); ?>">
	</div>

	<div id="xoros-dexia" class="span3">
		<h3 class="titlos-eikonas">What do i win?</h3>
		<img class="img-rounded" style="width:250px;margin:0 0 10px 0px;" src="<?php echo $this->baseUrl("images/sketch/epixeirhseis.png"); ?>">
		<p class="getinvolvedp hidden">He has graduated from the Department of Economics of Aristotle university. </p>
		<br>
	</div>
</div>


