
<div class="row howItWorks ">
	<div class="span12 text-center" >
		<?php /*<div id="myCarousel" class="carousel slide">
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
				<li data-target="#myCarousel" data-slide-to="3"></li>
				<li data-target="#myCarousel" data-slide-to="4"></li>
			</ol>
			<!-- Carousel items -->
			<div class="carousel-inner">
				<?php foreach ($this->information as $dataitem) {?>
				
					<div class="<?php if ($dataitem['id2']=="firstStep") echo "active"; ?> item">
						<div class="row pagination-centered">
						<div class="span6 offset2">
							<img class="sketch" src='<?php echo $this->baseUrl("images/sketch/".$dataitem['image']); ?>'>
						</div>
						</div>
						<?php /*<div class="carousel-caption sketchText">
							<?php echo $dataitem['text']; ?>
						</div> *?>
						
					</div>
				<?php } ?>
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next" >&rsaquo;</a>
		</div>
		*/ ?>
		<img  src='<?php echo $this->baseUrl("images/sketch/HowItWorksInfo.png"); ?>'>
	</div>
</div>	

	

