
<div class="row-fluid">
	<div class="span4" >
				<span>
					<img class="faces img-polaroid-circle" src="<?php echo $this->baseUrl("images/teamPhotos/ntempos.jpg"); ?>">
				</span>
			<div>
				<h2 class="media-heading">Dimitrios Ntempos</h2>
				<h4>Business Development Manager, Founder</h4>
				<p>He has graduated from the Department of Economics of Aristotle university. 
				During those years he attended student exchange programmes in Sweden and France gaining multicultural experiences. 
				By October 2012 he holds an MSc at "Informatics and Management" from the Computer Science Departement of Aristotle. 
				His working experience include traineeships at Greek ministry of foreign affairs, Hellenic post bank and a Consulting company. 
				He is a co-founder of SocialGreen where he works on the Business Development of the project.</p>
			</div>
	</div>
	<div class="span4">
			<span>
				<img class="faces img-polaroid-circle" src="<?php echo $this->baseUrl("images/teamPhotos/almpanidis.jpg"); ?>">
			</span>
			<div>
				<h2 class="media-heading">Evangelos Almpanidis</h2>
				<h4>Electronic engineer, Co-Founder</h4>
				<p>Born and raised in Thessaloniki. He is a graduate of the department of electronics, Alexandreio Technological Education Institute of Thessaloniki and has the capabilities to carry out the procedures of both digital and analog electronics design. 
				His main interests contain embedded software and hardware issues, using FPGA's and microcontrollers.
				 He is the electronic engineer of Social Green having developed the project's prototype bin. 
				Furthermore he has worked as an embedded developer in elevator industry and as technical personnel at A.T.E.I(digital labs I&amp;II). 
				In his free time he is getting involved with graphic design.</p>
			</div>
	</div>
	
	<div class="span4" >
		<span>
			<img class="faces img-polaroid-circle" src="<?php echo $this->baseUrl("images/teamPhotos/papadopoulos.jpg"); ?>">
			</span>
		<div>
				<h2 class="media-heading">Konstantinos Papadopoulos</h2>
				<h4>IT Manager, Co-Founder</h4>
				<p>Born and raised in Thessaloniki. He is a graduate of the department of electronics, Alexandreio Technological Education Institute of Thessaloniki and has the capabilities to carry out the procedures of both digital and analog electronics design. 
				His main interests contain embedded software and hardware issues, using FPGA's and microcontrollers.
				 He is the electronic engineer of Social Green having developed the project’s prototype bin. 
				Furthermore he has worked as an embedded developer in elevator industry and as technical personnel at A.T.E.I(digital labs I&II). 
				Én his free time he is getting involved with graphic design.</p>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span3 offset3">
		<span>
				<img class="faces img-polaroid-circle" src="<?php echo $this->baseUrl("images/teamPhotos/lapatas.png"); ?>">
		</span>
		<div>
			<h2 class="media-heading">George Lapatas</h2>
			<h4>Lead Software Developer</h4>
			<p>Born and raised in Thessaloniki, George always show passion for technology, sports and travels. 
				He attends the University of Peloponnese where he complete his studies at the Department of Computer Science and Technology and currently involving with the SocialGreen as a Web programmer. 
					In the mean time he is a swimmer and participate in swimming competitions. He has traveled to Italy, New York and many greek islands, his next big trip will be London.</p>
		</div>
	</div>
	<div class="span3" >
		<span>
			<img class="faces img-polaroid-circle" src="<?php echo $this->baseUrl("images/teamPhotos/karanaftis.jpg"); ?>">
		</span>
			<div>
				<h2 class="media-heading">Antonis Karanaftis</h2>
				<h4>Lead Designer</h4>
				<p>Born in Thessaloniki, he is about to graduate from the department of Graphic Design, Technological Educational Institute of Athens. 
				His working experience contains printing and graphic design positions. 
				In his free time, Antonis enjoys photo shooting and animation. 
				He is the Art Director of Social Green where he handles both digital and printed design projects.</p>
			</div>
	</div>
</div>
